sot/chandra_models

chandra_models/xija/pftank2t/pftank2t_spec.json
This branch includes updated Fuel Tank model parameters approved by the Thermal Working Group on Friday March 20th, 2015.
=> Convert pftank2t model to linear paramaters and refit

chandra_models/xija/psmc/psmc_spec.json
This model was approved by both the TWG and MPCWG.
=> Update PSMC model due to observed errors during OCT1915 schedule

chandra_models/xija/aca/aca_spec.json
This update adds some bad time spans and changes some P parameters. Further fitting of the dP parameters (and other parameters) did not result in a noticeable increase in accuracy so these changes were discarded.
=> Update ACA model: Jan 22, 2016

chandra_models/xija/aca/aacccdpt_fit_snapshots.json, chandra_models/xija/aca/aca_fit_script.py, chandra_models/xija/aca/aca_spec.json
This is a routine update to the ACA model.
=> Update ACA model, include fit progress (snapshots) and fit script

chandra_models/xija/psmc/psmc_spec.json
See first comment below for description of the model, and validation results.
=> 2017 fit to model with DA heater off

chandra_models/__init__.py, chandra_models/xija/dea/dea_spec.json
This requires an update to Xija that allows one to specify custom power coefficients.
=> Update DEA spec, includes custom power coefficients

chandra_models/xija/dpa/dpa_spec.json
January 08 recal of the 1DPAMZT thermal model including making 3xx0 the same as 3xx1.
=> January 08 Recalibration of the 1DPAMZT Thermal Model

chandra_models/__init__.py, chandra_models/xija/aca/aca_spec.json
Based on notebook results (URL in separate email).  This gives results:
=> Update solarheat bias for mixed-IRU heat

chandra_models/__init__.py, chandra_models/xija/aca/aca_spec.json
=> Revert "Update solarheat bias for mixed-IRU heat"

chandra_models/xija/pline/pline03t_model_spec.json
Approved during May 14 Thermal Working Group meeting.
=> New pline03t model specification

chandra_models/xija/pline/pline04t_model_spec.json
Approved during May 14 Thermal Working Group meeting.
=> New pline04t model specification

chandra_models/xija/tcylaft6/tcylaft6_fit_log.json, chandra_models/xija/tcylaft6/tcylaft6_fit_script.py, chandra_models/xija/tcylaft6/tcylaft6_spec.json
Approved during June 6th out of cycle TWG.
=> Update TCYLAFT6 model parameters

chandra_models/__init__.py, chandra_models/xija/acisfp/acisfp_spec.json
This recalibration involves the following:
* Added new ACIS state power coefficients
* 1CBAT node did not have bias parameters for different SIM-Z positions 
=> October 2019 recalibration of ACIS FP model

chandra_models/__init__.py, chandra_models/xija/dpa/dpa_spec.json
This corrects the parameter file to match the model approved on December 10th, 2019.
=> Update DPA paramters to values approved on Dec 10th, 2019

chandra_models/__init__.py, chandra_models/xija/fwdblkhd/4rt700t_spec.json
This updates the OBA model to account for the drop in heat load resulting from disabling the stuck on telescope zone 50 heater.
=> Add step power for zone 50

chandra_models/xija/dpa/dpa_spec.json
This updates the DPA model parameters.
=> Update DPA model parameters

chandra_models/__init__.py, chandra_models/xija/pftank2t/pftank2t_spec.json, chandra_models/xija/pftank2t/pftank2t_spec_with_cossrbx.json
This PR updates the IPS Fuel Tank model parameters with a general refit ~~, and updates the ACA limits (ACA model parameters remain unchanged).~~
=> Update Fuel Tank Model Parameters

chandra_models/__init__.py, chandra_models/xija/dea/dea_spec.json, chandra_models/xija/dpa/dpa_spec.json
This updates the DPA and DEA limits. No changes were made that affect model performance.
=> New dpa dea limits may 2022

chandra_models/xija/hrc/cea_spec.json
This PR added the new HRC CEA model.
Modified Files:
None
Files Added:
./chandra_models/xija/hrc/cea_spec.json (md5 51340b73ff30d34908e8f61ad3aaed44)
Files Removed:
None
=> Add new HRC CEA model

chandra_models/__init__.py, chandra_models/xija/aca/aca_spec.json
This updates the ACA model with a step power shift to account for the TFTE heater setpoint change, and a general parameter refit.
=> Update ACA model with preliminary power shift for TFTE setpoint change

chandra_models/xija/fwdblkhd/4rt700t_spec.json
This updates the OBA model with a step power shift to account for the TFTE heater setpoint change, and a general parameter refit.
=> Update OBA model with preliminary power shift for TFTE setpoint change

chandra_models/xija/mups_valve/pm1thv1t_spec.json
This is a new model for the MUPS1A thruster valve.
=> Add initial mups1a model

chandra_models/__init__.py, chandra_models/xija/aca/aca_spec.json
This PR modifies the ACA thermal model by adding the power step function at 2022:320. No other parameters were modified.
aca_spec.json
Files Added:
None
Files Removed:
None
=> ACA Model: Step Power Added at 2022:320

chandra_models/__init__.py, chandra_models/xija/acisfp/acisfp_spec.json, chandra_models/xija/acisfp/acisfp_spec_matlab.json, chandra_models/xija/dea/dea_spec.json
This PR updates the ACIS FP and 1DEAMZT models. 
For the ACIS FP model:
* Reworked solar heat pitch parameters.
* Updated bad times.
* Made small adjustments to the ACIS state power coefficients to reflect current operating modes.
* Performed a general re-fit of all parameters. 
All parameters were fit over the last 365 days of data previous to 2023:130. `solarheat*__dP*` parameters were fit over 900 days of data previous to 2023:130.
Current flight model dashboard plot with radzones included:
New model with radzones included:
Current flight model dashboard plot for observations only:
New model for observations only:
Pitch bin plots:
ACIS state power plot:
For the 1DEAMZT model:
* Updated bad times.
* Made small adjustments to the ACIS state power coefficients to reflect current operating …
=> ACIS FP and 1DEAMZT model updates

chandra_models/__init__.py
This increments the version to 3.50.1 in support of PR #113 (already merged).
=> Increment version to 3.50.1

chandra_models/__init__.py, chandra_models/xija/dpamyt/dpamyt_spec.json
Model Specification file for the new 1DPAMYT thermal model
=> New 1 dpamyt model

chandra_models/xija/pline/pline03t_model_spec.json, chandra_models/xija/pline/pline04t_model_spec.json
This PR updates the PLINE03T and PLINE04T caution high limits to match those listed in the TDB, and adds the TDB caution low limits.
- chandra_models/xija/pline/pline03t_model_spec.json: Limit updates only
- chandra_models/xija/pline/pline04t_model_spec.json: Limit updates only
=> Update PLINE odb caution high limits, add odb caution low limits

chandra_models/xija/fwdblkhd/4rt700t_spec.json
This PR updates several OBA limits to match the latest guideline and G_LIMMON updates.
- chandra_models/xija/fwdblkhd/4rt700t_spec.json: Limit updates only
=> Update OBA Limits

chandra_models/__init__.py, chandra_models/xija/fwdblkhd/4rt700t_spec.json
OBA Model full long/short term parameter refit. Updated planning high to 112F. Incremented version to 3.58.
=> OBA model refit, planning high increase to 112F

chandra_models/__init__.py, chandra_models/xija/pftank2t/pftank2t_spec.json
Tank planning limit increase to 125F.
=> Tank Planning Limit Increase October 2024

chandra_models/__init__.py, chandra_models/xija/aca/aca_spec.json
Added step power function on 2024:247. Incremented version to 3.60
=> ACA Model Update Oct 2024

chandra_models/__init__.py, chandra_models/xija/hrc/cea_spec.json
This updates the HRC CEA model with a full parameter refit.
=> Update CEA model

chandra_models/__init__.py, chandra_models/xija/hrc/cea_spec.json
This PR adjusts the 2CEAHVPT planning.warning.high limit from 10.0C to 9.5C, and the version from 3.63 to 3.63.1.
=> Hrc limit change feb 2025

chandra_models/__init__.py, chandra_models/xija/fwdblkhd/4rt700t_spec.json
This PR includes a full refit of most OBA parameters,  and the addition of a heater power input to model the impact of the periscope heater on the OBA model.
chandra_models/__init__.py: version increment to 3.64
chandra_models/xija/fwdblkhd/4rt700t_spec.json: full general parameter update, heater power input added
=> OBA Model Update March 2025

chandra_models/__init__.py, chandra_models/xija/tpc_fsse/tpc_fsse_spec.json
This PR adds a new thermal model, predicting temperature for the TPC_FSSE (Fine Sun Sensor Electronics).
Modified Files:
./chandra_models/\_\_init\_\_.py
Files Added:
./chandra_models/xija/tpc_fsse/tpc_fsse_spec.json
Files Removed:
None
This new TPC_FSSE model (tpc_fsse_spec.json) requires changes to the FOT MATLAB Tools
=> New Model for TPC_FSSE
