- chandra_models/version.py
- chandra_models/xija/dpa/dpa_spec.json
For reference the new DPA spec file has MD5 sum = dae62ecada5039bd481f5a3e6dbda718.  This requires xija version 0.7.
**Before:**
**After:**
> Update DPA model to include off-nominal roll heating

- chandra_models/xija/dea/dea_spec.json
This new specification for the DEA temperature model incorporates off-nominal roll in the same manner as the DPA model.
Examples of model validation for recent loads:
JAN2516A
Current Model: http://cxc.cfa.harvard.edu/acis/DEA_thermPredic/JAN2516/oflsa/
New Model: http://cxc.cfa.harvard.edu/acis/tmp/dea_jan2516a/
FEB0816B
Current Model: http://cxc.cfa.harvard.edu/acis/DEA_thermPredic/FEB0816/oflsb/
New Model: http://cxc.cfa.harvard.edu/acis/tmp/dea_feb0816b/
> New 1DEAMZT model specification, with off-nominal roll incorporated

- chandra_models/xija/psmc/psmc_spec.json
New PSMC (1PDEAAT) model with off-nominal roll dependence and the following features:
- Fit epoch is set to 2015:250.  This does change the numerical value of the P parameters, but the evaluated solar heat input at recent times is very close to your values.  I have verified that the residual vs. data plot looks similar, and I invite you to do the same.
- Long term evolution (*__dP_*) parameters have been set to 0.1.  When I reset the epoch to 2015:250 (vs. the original of 2013:001) and refit the dP values, the results had a mean of around +0.1, with scatter that is unphysical.  My takeaway is that the data cannot constrain those parameters.  If we had sufficiently fast computers then running "conf" would show large uncertainties on those parameters.  So my recommendation for the PSMC …
> PSMC model with roll dependence and updated params

- setup.py
This is needed so that `conda list` manages this package properly.
> Use setuptools not distutils

- chandra_models/xija/dea/dea_spec.json
- chandra_models/xija/dpa/dpa_spec.json
- chandra_models/xija/psmc/psmc_spec.json
This PR updates the model specifications for the 1DPAMZT, 1DEAMZT, and 1PDEAAT models. 
It has the following features:
- The 1DPAMZT and 1DEAMZT models use the new xija `SolarHeatHrcOpts` class which includes the bias parameters for HRC-S and HRC-I SIM positions.
- The state power coefficients for the 1DEAMZT and 1DPAMZT models have been refactored for simplicity and to reflect better the actual physical states of their respective electronics boxes.
- A new pseudo-node has been added to the 1DPAMZT model, which has solar heating as inputs and is coupled to 1DPAMZT. This improves the fit significantly. 
- The state power coefficients have been recalibrated for 3-FEP operation in the belts.
- `dP` parameters in `SolarHeatHrcOpts` have had their minima set to zero.
- A general recalibration …
> July 2018 recalibration of 1DPAMZT, 1DEAMZT, and 1PDEAAT thermal models

- chandra_models/xija/dpa/dpa_spec.json
These two power coefficients had incorrect names. Parameter values are still the same. It appears that this does not affect model performance at all, but this is still under investigation.
> [bugfix] incorrect names for power coefficients

- chandra_models/__init__.py
- chandra_models/xija/pline/pline03t_model_spec.json
- chandra_models/xija/pline/pline04t_model_spec.json
This includes two new Xija models to predict PLINE03T and PLINE04T. These models are not  approved for production use at this time, however they are ready for testing in production tools.
> New Xija PLINE Models

- chandra_models/__init__.py
- chandra_models/xija/dpa/dpa_spec.json
Update DPA parameter fit. This fit uses the new solar heat option (xija PR# 66 "Add option for multiplicative yearly dependence of solar heating"), which is included in Xija version 4.15 or later.
> Update DPA Parameters

- chandra_models/__init__.py
- chandra_models/xija/pline/pline03t_model_spec.json
- chandra_models/xija/pline/pline04t_model_spec.json
This PR updates the PLINE03T and PLINE04T thermal models. Aside from a general refit of the model parameters, each of these models have been updated use the new second order Runga Kutta integration method (evolve_method=2), and the multiplicative solar heat component. These models require Xija version 4.17 or later.
> Update PLINE models, Increment version

- chandra_models/xija/aca/aca_spec.json
This updates the ACA model to account for the drop in heat load resulting from the IRU reconfiguration that occurred on July 31st, 2020.
> New aca summer 2020

- chandra_models/__init__.py
- chandra_models/xija/pftank2t/pftank2t_spec.json
- chandra_models/xija/pftank2t/pftank2t_spec_with_cossrbx.json
This PR updates the tank model parameters, and adds a solar heat pitch value at 180 degrees. 
The fit was originally performed using a version of the model that included heat input from SSR-B via COSSRBX, however given SSR-B could be turned on autonomously (such as via a rollover), resulting in a larger than desired error in the model, this capability was removed. The final version of this model started with the newly fit version that included the SSR-B power component, the SSR-B power input was then removed, and only the model solar heat bias was refit to recenter the error. This strategy results in a mean error of approximately 1F at all times, but reduces the error amplitude on a week to week basis.
> Update tank model parameters

- chandra_models/xija/aca/aca_spec.json
This implements the change in the ACA planning limit that was approved at SS&AWG 6/23 and at MPCWG 6/16.
This is a precursor for corresponding updates in proseco and potentially MATLAB tools to use the new `limits` values.
> Add planning high and penalty high limits for ACA xija model

- chandra_models/__init__.py
- chandra_models/xija/acisfp/acisfp_spec.json
This is a recalibration of the ACIS FP xija thermal model. 
* Added two new elements to `bad_times`
* Reduces the number of ACIS state power coefficients (not enough data to discriminate between `4xx0` and `4xx1`, etc.)
* Added pitch bins at 60 and 105 degrees
* Uses `evolve_method` = 2 for new ODE solver
* Adds `limits` directory, but waiting to see how PR #75 gets sorted out
To facilitate a more fair comparison, in the following plots I have added the two new bad times to the flight model Note that dashboard plots with radzones masked are also included, since we care more about model performance during the science orbit.
Current flight model dashboard plot:
Current flight model dashboard plot, radzones masked:
Proposed flight model dashboard plot:
Proposed …
> Summer 2021 ACIS Focal Plane model recalibration

- chandra_models/__init__.py
- chandra_models/xija/fwdblkhd/4rt700t_spec.json
This release updates the OBA thermal model to include a LETG-specific thermal limit. No changes were made that affect model performance.
- chandra_models/xija/fwdblkhd/4rt700t_spec.json
- chandra_models/__init__.py
> Add LETG specific planning limit to OBA model

- chandra_models/xija/aca/aca_spec.json
This PR increases both the planning.warning.high and planning.penalty.high limits for the ACA model. This is a limit-only update.
> Increase ACA planning limits

- chandra_models/xija/aca/aca_fit_script_full_fit.py
- chandra_models/xija/aca/aca_spec_msid_state_power_fa6.json
This updates the ACA model with a hardcoded step increase in power starting 2022:040:17:31:50 to accommodate the FA6 heater state. Note that once the FA6 is turned off, this model will need to be adjusted to reflect the new state.
> Update ACA model to include impact of FA6 heater

- chandra_models/__init__.py
- chandra_models/xija/mups_valve/pm2thv1t_spec_matlab.json
This PR adds back the planning and caution limits for the MUPS2A `pm2thv1t_spec_matlab.json`  model.
> Add limits to pm2thv1t_spec_matlab.json

- chandra_models/__init__.py
- chandra_models/xija/aca/aca_spec.json
PR #96 makes the following changes:
- `aca_spec.json`: Increments `planning.penalty.high` from -6.2C to -5.5C, Increments `planning.warning.high` from -5.2C to -4.5C. 
- `__init__.json`: Increment version from 3.44 to 3.45 (major version number increment intended to account for ACA drift model inclusion as well)
Files Added:
- None
Files Removed:
- None
> Increase ACA limits, increment version

- chandra_models/xija/fwdblkhd/4rt700t_spec.json
This PR updates the `planning.warning.high` limit from 103F to 106F.
> Update 4RT700T planning.warning.high limit

- chandra_models/xija/aca/aca_spec.json
Per discussion at the SS&AWG and TWG, the ACA penalty limit is being effectively eliminated from use in proseco and sparkles evaluation of catalogs.
Per discussion at the Matlab WG on 6/14, we are implementing this by making the penalty limit be 0.5 deg higher than the planning limit. In all realistic cases this mean the penalty will not apply.
To be done by the FOT.
> Update penalty limit to -4.0 C in aca_spec.json

- chandra_models/__init__.py
- chandra_models/xija/acisfp/acisfp_spec.json
- chandra_models/xija/acisfp/acisfp_spec_matlab.json
- chandra_models/xija/hrc/cea_spec.json
This PR includes the following changes:
- chandra_models/xija/acisfp_spec.json: Add -105.0C hot ACIS "b" limit
- chandra_models/xija/acisfp_spec_matlab.json: Add -105.0C hot ACIS "b" limit
- chandra_models/xija/cea/cea_spec.json: decrease planning limit from 10.0C to 9.5C
- chandra_models/__init__.py: increment version from 3.49 to 3.49.1
> Add -105C ACISFP limit, decrease CEA limit to 9.5C

- chandra_models/xija/aca/aca_spec.json
Per prior discussion this removes the ACA penalty limit from the ACA thermal model spec file. Tools that use this limit have been modified to work with or without this limit in the spec file:
- https://github.com/sot/proseco/pull/384
- https://github.com/sot/starcheck/pull/429
- MATLAB tools ticket  MATLAB-12026
This will remove the `["limits"]["aacccdpt"]["planning.penalty_high"]` attribute
Julia reported verbally that she tested this in MATLAB tools. The individual PR's have been likewise tested.
> Update aca_spec.json to remove the ACA penalty limit

- chandra_models/__init__.py
- chandra_models/xija/mups_valve/pm1thv2t_spec.json
- chandra_models/xija/mups_valve/pm2thv1t_spec_matlab.json
This PR updates the two production mups model spec files to reflect the new `planning.warning.high` thermal limit of 215F and bumps the version from 3.52 to 3.52.1.
- chandra_models/xija/mups_valve/pm1thv2t_spec.json: Limit updates only
- chandra_models/xija/mups_valve/pm2thv1t_spec_matlab.json: Limit updates only
- chandra_models/\_\_init\_\_.py: version increment
> Update limits in currently used mups model spec files

- chandra_models/xija/fwdblkhd/4rt700t_spec.json
This PR updates the OBA Forward Bulkhead model with new separate OTG limits.
- chandra_models/xija/fwdblkhd/4rt700t_spec.json: Limit updates only
> Update OTG limits to hetg: 73, letg: 77

- chandra_models/__init__.py
- chandra_models/xija/hrc/cea_spec.json
This PR updates the HRC CEA planning limit to 10C, consistent with the currently approved guideline.
- chandra_models/\_\_init\_\_.py: version increment to 3.53.1
- chandra_models/xija/hrc/cea_spec.json: Limit updates only
> Update HRC limit back to 10C, Increment version to 3.53.1

- chandra_models/__init__.py
- chandra_models/xija/mups_valve/pm1thv2t_spec.json
- chandra_models/xija/mups_valve/pm2thv1t_spec_matlab.json
This PR updates the MUPS planning limit to 220F, consistent with the currently approved guideline.
- chandra_models/__init__.py: version increment to 3.53.2
- chandra_models/xija/mups_valve/pm1thv2t_spec.json: Limit updates only
- chandra_models/xija/mups_valve/pm2thv1t_spec_matlab.json: Limit updates only
> Update MUPS planning limit to 220F, increment version to 3.53.2

- chandra_models/__init__.py
- chandra_models/xija/aca/aca_spec.json
This PR includes a full parameter update for the ACA thermal model. Both long and short term parameters were refit, and solarheat bias and amplitude parameters were slightly altered. 
chandra_models/init.py: version increment to 3.54
chandra_models/xija/aca/aca_spec.json: Full long/short term parameter refit
> Full long/short term parameter refit, incremented version to 3.54

- chandra_models/__init__.py
- chandra_models/xija/acisfp/acisfp_spec.json
This PR contains an "interim" ACIS FP thermal model that does not require a revision to the MATLAB FOT Tools, so that we can obtain better predictions for the ACIS FP temperature in the interim while we wait for the model in PR #132 (which does require such a revision) to be included. 
Fits were performed for ~300 days of data stopping at until 2024:200, except the `dP` solarheat parameters which were fit over 900 days of data.
* Update solarheat epoch to a more recent time
* Added new dP parameters near pitches of ~100-110
* Add one bad time for recent safing action
Current flight dashboard plot, all data:
Current flight dashboard plot, science orbit only:
Notice that around DOY 2024:080 the model's performance began to noticeably degrade.
This PR's …
> Interim ACIS FP thermal model

- chandra_models/__init__.py
- chandra_models/xija/mups_valve/pm1thv2t_spec.json
This PR updates the MUPS1B thermal model with a fully refitted version. Fit included data for at least five years, ending on 180:2024. Any model performance metrics including data past this day are purely independent and can be used to indicate expected future performance.
- chandra_models/\_\_init\_\_.py: version increment to 3.57
- chandra_models/xija/mups_valve/pm1thv2t_spec.json: Full model refit
> Update MUPS1B Model

- chandra_models/__init__.py
- chandra_models/xija/acisfp/acisfp_spec.json
- chandra_models/xija/acisfp/acisfp_spec_matlab.json
This is an update to the ACIS FP thermal model. This is an improvement over the recently installed FP thermal model for schedules which alternate between HRC and ACIS observations in the pitch range of ~100-120 degrees.
Fits were performed for 365 days of data stopping at until 2024:268 except the `dP` solarheat parameters, which were fit over 800 days of data.
* Implemented SIM-Z dependent pitch bins for the `1cbat` node
* Implement a new `MsidStatePower` component for `215pcast` for times when the HRC is on and observing
Flight model dashboard plot, all data:
New model dashboard plot, all data:
Flight model dashboard plot, science orbit:
New model dashboard plot, science orbit:
sim_px pitch bins:
1cbat pitch bins:
Power state plot:
> ACIS FP model update: Add in HRC heating and SIM-Z dependent solar heating

- chandra_models/xija/fwdblkhd/4rt700t_spec.json
This adds HETG and LETG planning limits to the `4rt700t_spec.json` file to cover cases when the upper limits are different (lower) than the upper health and safety limit.
These are the only changes made:
```
"planning.warning.high.hetg": 112,
"planning.warning.high.letg": 112,
```
> Add planning.warning.high hetg and letg limits

- chandra_models/xija/acisfp/acisfp_spec.json
Now that the MATLAB 070 release has been approved and is being used in flight, we can copy the `acisfp_spec_matlab.json` file over to the `acisfp_spec.json` file so that the latter can be used by ACIS and SOT MP in their thermal model runs.
> Copy latest FP model from acisfp_spec_matlab.json to acisfp_spec.json

- chandra_models/__init__.py
- chandra_models/xija/aca/aca_spec.json
This PR includes a full refit of most ACA parameters.
- chandra_models/init.py: version increment to 3.62
- chandra_models/xija/aca/aca_spec.json: full parameter update
The following parameters were refit:
- solarheat P
- solarheat dP
- solarheat amplitude
- heatsink tau, T
- coupling
Other changes of note:
- I increased the mask temperature to -13.0C
- I set the solarheat bias to zero
- The fit was performed using data from 2021:001 to 2024:350
- I added a power step on day 2024:334
> December 2024 ACA Model Refit

- chandra_models/__init__.py
- chandra_models/xija/aca/aca_spec.json
This PR includes a full refit of most ACA parameters, the removal of the two recent step power inputs, and a repurposed heater power input to model the impact of the periscope heater on the ACA model.
- chandra_models/\_\_init\_\_.py: version increment to 3.63
- chandra_models/xija/aca/aca_spec.json: full general parameter update, step power inputs removed, heater power input added
> New ACA Model January 2025

- chandra_models/xija/mups_valve/pm1thv2t_spec.json
- chandra_models/xija/mups_valve/pm2thv1t_spec_matlab.json
This PR updates the MUPS planning limit to 225F, consistent with the currently approved guideline.
chandra_models/xija/mups_valve/pm1thv2t_spec.json: Limit updates only
chandra_models/xija/mups_valve/pm2thv1t_spec_matlab.json: Limit updates only
> Update MUPS Planning Limits to 225F

- chandra_models/__init__.py
- chandra_models/xija/pftank2t/pftank2t_spec.json
- chandra_models/xija/pftank2t/pftank2t_spec_with_cossrbx.json
This PR includes a full refit of most Tank model parameters. SSR-B is included in the model for fitting purposes, then taken out since the SSR-B state can not be reliably predicted. The solar heat bias is used to shift the error to the median.
chandra_models/init.py: version increment to 3.66.0
chandra_models/xija/pftank2t/pftank2t_spec.json: full general parameter update.
chandra_models/xija/pftank2t/pftank2t_spec_with_cossrbx.json: full general parameter update.
Files Added: 
None
Files Removed: 
None
> PFTANK2T Model Update April 2025

- chandra_models/__init__.py
- chandra_models/xija/mups_valve/pm1thv2t_spec.json
- chandra_models/xija/mups_valve/pm2thv1t_spec_matlab.json
This PR updates the MUPS planning limit to 227.5F, consistent with the currently approved guideline.
chandra_models/xija/mups_valve/pm1thv2t_spec.json: Limit updates only
chandra_models/xija/mups_valve/pm2thv1t_spec_matlab.json: Limit updates only
> Update MUPS Planning Limits to 227.5F

- chandra_models/__init__.py
- chandra_models/xija/aca/aca_spec.json
- chandra_models/xija/pline/pline03t_model_spec.json
- chandra_models/xija/pline/pline04t_model_spec.json
This PR includes a full parameter refit for the PLINE03T and PLINE04T models, as well as an update to the ACA planning limit (increased to -2.1C).
chandra_models/init.py: version increment to 3.68.0
chandra_models/xija/pline/pline03t_model_spec.json: full general parameter update
chandra_models/xija/pline/pline04t_model_spec.json: full general parameter update
chandra_models/xija/aca/aca_spec.json: limit update only
> PLINE Model Update August 2025

- chandra_models/__init__.py
- chandra_models/xija/acisfp/acisfp_spec.json
- chandra_models/xija/acisfp/acisfp_spec_matlab.json
This is an update to the ACIS FP thermal model. Fits were performed for 365 days of data stopping at until 2025:209 except the `dP` solarheat parameters, which were fit over 900 days of data.
* Added a new pitch bin at 70 degrees to the `solarheat__sim_px` node
* Changed epoch value for long-term pitch behavior to something more recent
* Added a bad time corresponding to the telemetry loss on DOYs 2025:163-2025:164
Flight model dashboard plot, all data:
New model dashboard plot, all data:
Flight model dashboard plot, science orbit:
New model dashboard plot, science orbit:
sim_px pitch bins:
1cbat pitch bins:
Power state plot:
> Updated ACIS FP model: Summer 2025
